import { useEffect, useState } from 'react'
const today = new Date().toISOString().slice(0, 10)
export default function TransferModal({ allocation, employees = [], open, onClose, onSubmit, busy }) {
  const [form, setForm] = useState({ toUser: '', toDepartment: '', reason: '', transferDate: today })
  useEffect(() => { if (allocation) setForm({ toUser: '', toDepartment: '', reason: '', transferDate: today }) }, [allocation])
  if (!open || !allocation) return null
  const change = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  const submit = async (event) => { event.preventDefault(); if (!window.confirm('Are you sure you want to submit this transfer request?')) return; await onSubmit({ allocation: allocation._id, ...form }); }
  return <div className="allocation-modal-backdrop"><form className="allocation-modal allocation-form" onSubmit={submit}><h3>Transfer request</h3><p>Current holder: <b>{allocation.assignedTo?.fullName}</b></p><label>New holder<select required value={form.toUser} onChange={(event) => { const employee = employees.find((item) => item._id === event.target.value); change('toUser', event.target.value); if (employee?.department) change('toDepartment', employee.department) }}><option value="">Select employee</option>{employees.filter((item) => item._id !== allocation.assignedTo?._id).map((item) => <option key={item._id} value={item._id}>{item.fullName}</option>)}</select></label><label>Department<input value={form.toDepartment} onChange={(event) => change('toDepartment', event.target.value)} /></label><label>Reason<textarea required value={form.reason} onChange={(event) => change('reason', event.target.value)} /></label><label>Transfer date<input type="date" min={today} required value={form.transferDate} onChange={(event) => change('transferDate', event.target.value)} /></label><div className="allocation-form-actions"><button type="button" onClick={onClose}>Cancel</button><button disabled={busy}>Submit request</button></div></form></div>
}
